name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set Docker Build
      uses: docker/setup-buildx-action@v3.11.1

    - name: Download a build artifact
      uses: actions/download-artifact@v5.0.0
      with:
        name: programa
    
    - name: Docker Login
      uses: docker/login-action@v3.5.0
      with:
        username: omateusvalente
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
    
    - name: Build and Push Docker Images
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: omateusvalente/go_ci:${{github.run_number}}
